parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\Application\Shared\Command\CommandHandlerInterface:
            tags: [messenger.message_handler]

    App\:
        resource: '../src/*'
        exclude: '../src/**/{Migrations}'

    App\Infrastructure\Shared\Bus\Command\MessengerCommandBus:
        arguments:
            - '@messenger.bus.command'
